#!/usr/bin/env python3
"""Generate WATokenMap.h from Baileys constants.ts"""
import re

# Baileys constants content (fetched from GitHub)
BAILEYS_CONSTANTS = '''
[TOKENS_DATA]
'''

def parse_token_arrays(content):
    """Parse SINGLE_BYTE_TOKENS and DOUBLE_BYTE_TOKENS from Baileys constants."""
    # Parse SINGLE_BYTE_TOKENS
    # The array ends with just ] followed by blank line then DOUBLE_BYTE_TOKENS
    sb_match = re.search(r"export const SINGLE_BYTE_TOKENS = \[(.*?)\]\s*\n\nexport", content, re.DOTALL)
    single_byte = []
    if sb_match:
        single_byte = re.findall(r"'([^']*)'", sb_match.group(1))
    
    # Parse DOUBLE_BYTE_TOKENS (array of arrays)
    db_match = re.search(r"export const DOUBLE_BYTE_TOKENS = \[(.*?)\] as const", content, re.DOTALL)
    double_byte = []
    if db_match:
        inner = db_match.group(1)
        # Split by sub-arrays
        depth = 0
        current = ""
        for ch in inner:
            if ch == '[':
                depth += 1
                if depth == 1:
                    current = ""
                    continue
            elif ch == ']':
                depth -= 1
                if depth == 0:
                    tokens = re.findall(r"'([^']*)'", current)
                    double_byte.append(tokens)
                    current = ""
                    continue
            if depth >= 1:
                current += ch
    
    return single_byte, double_byte

def escape_cpp(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')

def generate_header(single_byte, double_byte):
    lines = []
    lines.append("// Auto-generated from Baileys constants.ts — DO NOT EDIT MANUALLY")
    lines.append("// Generated by tools/gen_token_dicts.py")
    lines.append("#pragma once")
    lines.append("#include <map>")
    lines.append("#include <vector>")
    lines.append("#include <string>")
    lines.append("")
    
    # Double-byte tokens per dictionary
    lines.append(f"// Double-byte dictionaries: {len(double_byte)} dicts")
    for i, tokens in enumerate(double_byte):
        lines.append(f"// Dictionary {i}: {len(tokens)} tokens")
        lines.append(f"inline const std::vector<std::string> DOUBLE_BYTE_TOKENS_{i} = {{")
        for t in tokens:
            lines.append(f'    "{escape_cpp(t)}",')
        lines.append("};")
        lines.append("")
    
    # Lookup map: dict_index -> {byte_index -> token_string}
    lines.append("// Double-byte token lookup (dict -> (index -> string))")
    lines.append("inline const std::map<uint8_t, std::map<uint8_t, std::string>> DOUBLE_BYTE_TOKENS = {")
    for i, tokens in enumerate(double_byte):
        lines.append(f"    {{{i}, {{")
        for j, t in enumerate(tokens):
            lines.append(f'        {{{j}, "{escape_cpp(t)}"}},')
        lines.append("    }},")
    lines.append("};")
    lines.append("")
    
    # Dict count
    lines.append(f"constexpr size_t NUM_TOKEN_DICTS = {len(double_byte)};")
    lines.append(f"constexpr uint8_t DICT_BASE_TAG = 236; // DICTIONARY_0 through DICTIONARY_3")
    lines.append("")
    
    # Reverse lookup map: string -> {dict, index}
    lines.append("// Reverse lookup: string -> {dict (int8_t, -1 for single-byte), index}")
    lines.append("struct TokenRef { int8_t dict; uint8_t index; };")
    lines.append("inline const std::map<std::string, TokenRef> TOKEN_MAP = {")
    # Single-byte tokens (dict = -1)
    for i, t in enumerate(single_byte):
        lines.append(f'    {{"{escape_cpp(t)}", {{-1, {i}}}}},')
    # Double-byte tokens
    for i, tokens in enumerate(double_byte):
        for j, t in enumerate(tokens):
            lines.append(f'    {{"{escape_cpp(t)}", {{{i}, {j}}}}},')
    lines.append("};")
    lines.append("")
    
    return "\n".join(lines)

if __name__ == "__main__":
    import sys
    content = sys.stdin.read()
    single_byte, double_byte = parse_token_arrays(content)
    print(f"Parsed {len(single_byte)} single-byte tokens, {len(double_byte)} double-byte dicts", file=sys.stderr)
    for i, d in enumerate(double_byte):
        print(f"  Dict {i}: {len(d)} tokens", file=sys.stderr)
    
    header = generate_header(single_byte, double_byte)
    print(header)
